services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: stonks
      POSTGRES_PASSWORD: stonks
      POSTGRES_DB: stonks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
