import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

export const JOURNAL_TYPES_RESOURCE_URI = "stonks://reference/journal-types";

/**
 * The minimum ledger guidance an agent needs before composing a journal.
 * Keep examples wire-shaped: amounts, quantities, and FX values are strings.
 */
export const JOURNAL_TYPES_REFERENCE = [
  "# Stonks journal types and posting conventions",
  "",
  "## Wire invariants",
  "",
  "- `amountMinor` is a signed integer minor-unit string, never a JSON number.",
  "- `quantity` is a fixed-scale decimal string with at most 8 decimal places.",
  "- FX uses bigint-string `fxRateN` and positive bigint-string `fxRateD`.",
  "- `tradeDate` is `YYYY-MM-DD`; `sortKey` is assigned by the server.",
  "- A journal has at least two postings, and posting amounts must sum to zero.",
  "- Amounts are recorded in the household reporting currency. When supplied, a",
  "  posting's `currency` must equal that reporting currency.",
  "",
  "## Signed debit-positive convention",
  "",
  "Stonks uses signed, debit-positive postings: a positive amount is the debit",
  "or value received by an account, and a negative amount is the credit or value",
  "given up by an account. Think of a journal as moving value from a negative leg",
  "to a positive leg. The complete journal, not each posting, must balance to zero.",
  "",
  "For a deposit, the household cash account is positive and the EXTERNAL account",
  "is negative. For a buy, the investment account is positive and the funding",
  "account is negative. A credit-facility draw is negative on the facility account",
  "and must be fully covered by positive `facilityUses` lines.",
  "",
  "## Journal types",
  "",
  "- `DEPOSIT`: outside money into a household account.",
  "- `WITHDRAWAL`: household money to an external account.",
  "- `TRANSFER`: movement between household accounts.",
  "- `BUY`: positive quantity and cost on a security posting; funding is negative.",
  "- `SELL`: negative quantity and proceeds on a security posting.",
  "- `DIVIDEND`: dividend proceeds, optionally with a security posting.",
  "- `INTEREST_CHARGED`: a borrowing charge, optionally attributed to facility uses.",
  "- `INTEREST_EARNED`: interest income.",
  "- `FEE`: a posted fee.",
  "- `OPENING`: an opening balance or position; omit cost fields when unknown.",
  "- `CORPORATE_ACTION`: present in ledger history, but its action payload is not",
  "  yet supported by `record_journal`.",
  "",
  "## Posting shape",
  "",
  "Each posting has `accountId` and `amountMinor`, plus optional `currency`,",
  "`quantity`, `securityId`, `tradeCurrency`, `tradeAmountMinor`, `fxRateN`, and",
  "`fxRateD`. A journal may also contain `facilityUses`, each with `use`",
  "(`INVESTMENT`, `LENDING`, `PERSONAL`, or `OTHER`) and an `amountMinor` string.",
  "",
  "## Balanced examples",
  "",
  "Deposit 1,000.00 CAD into `cash` from the outside world:",
  "",
  "```json",
  "{",
  '  "type": "DEPOSIT",',
  '  "tradeDate": "2026-08-05",',
  '  "postings": [',
  '    { "accountId": "world", "amountMinor": "-100000" },',
  '    { "accountId": "cash", "amountMinor": "100000" }',
  "  ]",
  "}",
  "```",
  "",
  "Buy 100 XEQT for 2,500.00 CAD from cash:",
  "",
  "```json",
  "{",
  '  "type": "BUY",',
  '  "tradeDate": "2026-08-05",',
  '  "postings": [',
  '    {',
  '      "accountId": "brokerage",',
  '      "amountMinor": "250000",',
  '      "quantity": "100",',
  '      "securityId": "XEQT",',
  '      "tradeCurrency": "CAD",',
  '      "tradeAmountMinor": "250000"',
  "    },",
  '    { "accountId": "cash", "amountMinor": "-250000" }',
  "  ]",
  "}",
  "```",
  "",
  "Journals are immutable. To correct a posted journal, use",
  "`supersede_journal`; never edit or delete the original.",
].join("\n");

export function registerMcpResources(server: McpServer): void {
  server.registerResource(
    "journal-types",
    JOURNAL_TYPES_RESOURCE_URI,
    {
      title: "Journal types and posting conventions",
      description:
        "Signed debit-positive posting rules, supported journal types, wire shape, " +
        "and balanced examples for composing Stonks journals.",
      mimeType: "text/markdown",
    },
    (uri) => ({
      contents: [
        {
          uri: uri.href,
          mimeType: "text/markdown",
          text: JOURNAL_TYPES_REFERENCE,
        },
      ],
    }),
  );
}
